-- DropForeignKey
ALTER TABLE "NAV" DROP CONSTRAINT "NAV_isin_fkey";

-- AlterTable
ALTER TABLE "ISIN" ALTER COLUMN "isin" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "NAV" ALTER COLUMN "isin" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "NAV" ADD CONSTRAINT "NAV_isin_fkey" FOREIGN KEY ("isin") REFERENCES "ISIN"("isin") ON DELETE RESTRICT ON UPDATE CASCADE;
